apiVersion: apps/v1
kind: Deployment
metadata:
  name: hostinfo-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hostinfo-server
  template:
    metadata:
      labels:
        app: hostinfo-server
    spec:
      containers:
          - image: asia-northeast1-docker.pkg.dev/kzs-sandbox/toybox/hostinfo-server:v1
            name: hostinfo-server
            ports:
             - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: hostinfo-server
spec:
  ports:
    - name: grpc
      port: 8080
      protocol: TCP
  selector:
    app: hostinfo-server
  type: ClusterIP
  clusterIP: None
---